# Generated by Django 2.2.4 on 2019-08-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FileService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=64)),
                ('http_code', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XSSProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='XSSRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='httplog',
            name='content',
        ),
        migrations.AddField(
            model_name='httplog',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='httplog',
            name='header',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='httplog',
            name='host',
            field=models.TextField(default=''),
        ),
    ]
