# Generated by Django 2.2.4 on 2019-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190810_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileservice',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='fileservice',
            name='http_code',
        ),
        migrations.AddField(
            model_name='fileservice',
            name='headers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fileservice',
            name='is_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dnslog',
            name='content',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='fileservice',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='httplog',
            name='body',
            field=models.BinaryField(default=''),
        ),
    ]
