# Generated by Django 2.2.4 on 2019-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190813_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileservice',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
